<!DOCTYPE html>
<head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@1,500;1,700&family=Noto+Serif+HK&display=swap" rel="stylesheet">
  <meta name="description" content="A portal for indian users to register themself for covid vaccination." charset="utf-8">
  <link rel="stylesheet" href="styles.css">
  <title>COVID 19 VACCINATION PORTAL</title>
</head>
<span class = "bigtext">Get Vaccinated NOW!</span>
<br>
<button class="loginbutton" onclick="window.location.href='login.php';">Login</button>

<button class="signup" onclick="window.location.href='signup.php';">SignUp</button>
<?php
$sql="
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `vaccportal`
--

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `refno` int(10) NOT NULL,
  `name` tinytext NOT NULL,
  `mobil` text NOT NULL,
  `age` int(11) NOT NULL,
  `dob` year(4) NOT NULL,
  `id` int(11) NOT NULL,
  `loc` text NOT NULL,
  `gender` text NOT NULL,
  `dose` int(10) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`refno`, `name`, `mobil`, `age`, `dob`, `id`, `loc`, `gender`, `dose`) VALUES
(1, 'TEST1', '1111111111', 22, 2003, 999, 'bengaluru', 'Female', 1),
(2, 'TEST2', '2222222222', 32, 2023, 100, 'bengaluru', 'female', 2),
(3, 'TEST3', '3333333333', 24, 2023, 100, 'mysuru', 'non binary', 3),
(4, 'TEST4', '4444444444', 22, 2003, 999, 'bengaluru', 'male', 0),
(5, 'TEST5', '5555555555', 22, 2003, 999, 'looj', 'male', 0),
(6, 'TEST6', '6666666666', 22, 2003, 999, 'looj', 'male', 0),
(7, 'TEST7', '7777777777', 1, 2013, 1, '1', '1', 0),
(9, 'TEST999', '999', 22, 2003, 999, 'looj', 'male', 3),
(10, 'TEST987', '987', 22, 2003, 999, 'looj', 'male', 3),
(11, 'aaa', '987', 22, 2003, 999, 'looj', 'male', 3),
(12, 'testinfinity', '99999', 12, 2022, 99999, 'udupi', 'female', 3);

-- --------------------------------------------------------

--
-- Table structure for table `vaxdata`
--

CREATE TABLE `vaxdata` (
  `Centre` varchar(78) NOT NULL,
  `free/paid` varchar(6) NOT NULL DEFAULT 'FREE',
  `Location` varchar(30) NOT NULL DEFAULT 'N/A',
  `Register` varchar(255) NOT NULL DEFAULT 'https://selfregistration.cowin.gov.in/' COMMENT 'link'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `vaxdata`
--

INSERT INTO `vaxdata` (`Centre`, `free/paid`, `Location`, `Register`) VALUES
('Dhanush Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Baragi Hospital Bagalkot', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Daddenavar Hospital And Research Centre', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Shanti Hospital Bagalkot', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Kerudi Healthcare Private Limited Bagalkot', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Patil Medicare Multispeciality Hospital Bagalkot', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Sanjeevini Children And Eye Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Spandana Multispeciality Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('M S Kerudi Hospital And Research Centre Bagalkot', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Dr Katti Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Shakuntala multispeciality hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Guled Ortho Care Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Ashirwad Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Shri Banashankari Eye Hospital Bagalkot', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Ashraya Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('SNMC HSK Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Bests Kuntoji Multispeciality Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('MAHANTESH MULTI SPECIALITY HOSPITAL', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Dr R G Karudagimath Memorial Nursing Home Badami', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Dr A R Belgali Surgical Clinic And Maternity Home', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Arogyadham Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Riti life care Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Sai Aadhar Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Sharada Ortho Speciality Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Trishaladevi Super Speciality Eye Hospital', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('OrthoCare Multispeciality Hospital Rabkavi', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('PADMA HOSPITAL TERDAL', 'Paid', 'Bagalkote', 'https://selfregistration.cowin.gov.in/'),
('Jindal Sanjeevani Multi Speciality Hospital', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('Mahesh Nursing Home', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('Abhaya Hospital', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('KLS Hospital Hosapete', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('Umakanth Eye Hospital', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('Dipali Hospital', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('Citi Hospital', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('Arogyadhama Hospital unit of Shivanagouda Hosp Pvt', 'Paid', 'Ballari', 'https://selfregistration.cowin.gov.in/'),
('Shree Ortho And Trauma Centre', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Noble Care Childrens Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Vijaya Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Kapileshwar Orthopedic Trauma And Surgical Center', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Vijaya Ortho And Trauma Centre', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Yash Hospital Critical Care Centre', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Belgaum Childrens Hospital Pvt Ltd', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Life Care Multispeciality Hospital and Diagnostic', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('BHS Lakeview Heart And Super Speciality Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Shri Daneshwari Surgical And General Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Kle Centenary Charitable Hospital And Mrc', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Shri Sai Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Venugram Hospitals Belgaum Pvt Ltd', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Venus Multi Super Specialty Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Dakshata Hospitals Pvt Ltd', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Kles Dr Prabhakar Kore Hospital And Mrc', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Kle Societys Belgaum Cancer Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('BHS lakeview Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Dr Naiks Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Dr Navadgi Nursing Home', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Salagare Childrens And Eye Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Jeevan Maternity And Surgical Hospital Manjari', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Shri Mallikarjun Multispeciality Hospital Harugeri', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('SSJMECT ASHIRWAD NURSING AND MATERNITY HOME', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Shri S B Odeyar Memorial Hospital Harugeri', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('DANESHWARI MULTI SPECIALITY HEALTH CARE', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Rajiv Gandhi Rural Hospital And Mrc', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Shri Dhanvantari Nursing Home', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Shree Nursing Home Ainapur', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Padma Nursing Home', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Metri Hospital Athani', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Annapurna Multisepciality Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Jayaratna Eye Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Naikwadi Medical Center', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Karnatak Health Institute', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Dr B B Ghodageri', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Shri J G Co Operative Hospital Society Ltd', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Ganga Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('SUKH SHANTI SUPER SPECIALITY S4 HOSPITAL GOKAK', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Jayaratna Maternity And Laparoscopy Surgical Hospital', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Dr Balesh Kappalguddi', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('AROGYA ADHAAR HOSPITAL', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Atharv Ortho and Trauma care Hospital Gokak', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('KLES HOSPITAL ICU GOKAK', 'Paid', 'Belagavi', 'https://selfregistration.cowin.gov.in/'),
('Tathagat Heart Care Centre Llp', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Asian Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('B W Lions Superspeciality Eye Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Manipal Northside Hospital a unit of MHEPL', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Trinity Hospital And Heart Foundation', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('KIMS Hospital And Research Center', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('BMS Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Santosh Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('New varalakshmi hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('People Tree Hospitals', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Spine Care And Ortho Care Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Healthcare Global Enterprises Ltd', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('St Johns Medical College Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Sankara Eye Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Rainbow Childrens Medicare Private Limited', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Chinmaya Mission Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Specialist Health System Pvt Limited', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('New Janapriya Super Specialty Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('St Philomenas Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('East Point Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('HBS Hospital Trust', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('The Heart Center', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('SHIFAA HOSPITAL', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Bhagwan Mahaveer Jain Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('M S Ramaiah Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('M S Ramaiah Narayana Heart Centre', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Belaku Eye Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('BGS Global Institute of Medical Science and Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('PM Santosha Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Nethrakashi Eye Hospital And Micro Surgical Center', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('SI Vega Hospital Private Limited Regal Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Vydehi Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Prashanth Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Bangalore Nethralaya', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Nu Hospitals Pvt Ltd', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Rajarajeswari Medicalcollege And Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Medihope Hospitals And Research Centre Pvt Ltd', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Rainbow Childrens Medicare Private Limited Bannerghatta Road', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Sagar Hospitals', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Bharathy Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Vittala International Institute Of Ophthalmology', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Bhagwan Mahaveer Jain Hospital Girinagar', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Sanjeevini Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Sapthagiri Super Speciality Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Bangalore Cancer Centre Private Limited', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Aster CMI Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Raksha Multispeciality Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Samrudhi Eye Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Aveksha Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('SPARSH HOSPITAL RR Nagar', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Narayana Hrudayalaya Private Limited', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('The Eye Foundation', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('ACE Suhas Hospital', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('The Oxford Medical College Hospital and Research center', 'Paid', 'Bengaluru', 'https://selfregistration.cowin.gov.in/'),
('Nandi Multi Specialty Hospital', 'Paid', 'Bengaluru Rural', 'https://selfregistration.cowin.gov.in/'),
('Manasa Hospital', 'Paid', 'Bengaluru Rural', 'https://selfregistration.cowin.gov.in/'),
('Akash Hospital', 'Paid', 'Bengaluru Rural', 'https://selfregistration.cowin.gov.in/'),
('Leena Multispeciality Hospital', 'Paid', 'Bengaluru Rural', 'https://selfregistration.cowin.gov.in/'),
('MVJ Medical College And Research Hospital', 'Paid', 'Bengaluru Rural', 'https://selfregistration.cowin.gov.in/'),
('Sri Siddhartha Institute Of Medical Sciences', 'Paid', 'Bengaluru Rural', 'https://selfregistration.cowin.gov.in/'),
('Ramaiah Harsha Hospital', 'Paid', 'Bengaluru Rural', 'https://selfregistration.cowin.gov.in/'),
('New Rifah Hospital Basavakalyan', 'Paid', 'Bidar', 'https://selfregistration.cowin.gov.in/'),
('JSS HOSPITAL', 'Paid', 'Chamarajanagara', 'https://selfregistration.cowin.gov.in/'),
('Holy Cross Hospital', 'Paid', 'Chamarajanagara', 'https://selfregistration.cowin.gov.in/'),
('Manasa Sln Hospital Bagepalli', 'Paid', 'Chikkaballapur', 'https://selfregistration.cowin.gov.in/'),
('Someshwara Hospital', 'Paid', 'Chikkaballapur', 'https://selfregistration.cowin.gov.in/'),
('Prasad Hospital', 'Paid', 'Chikkaballapur', 'https://selfregistration.cowin.gov.in/'),
('Nandeeshwara Super Speciality Eye Hospital', 'Paid', 'Chikkaballapur', 'https://selfregistration.cowin.gov.in/'),
('Lakshmi Eye Hospital', 'Paid', 'Chikkaballapur', 'https://selfregistration.cowin.gov.in/'),
('Soumya Eye Hospital', 'Paid', 'Chikkaballapur', 'https://selfregistration.cowin.gov.in/'),
('Ashraya Hospital', 'Paid', 'Chikkamagaluru', 'https://selfregistration.cowin.gov.in/'),
('Vaatsalya Hospital', 'Paid', 'Chikkamagaluru', 'https://selfregistration.cowin.gov.in/'),
('Reticorn Eye Hospital', 'Paid', 'Chikkamagaluru', 'https://selfregistration.cowin.gov.in/'),
('Holy Cross Hospital Chikmagaluru', 'Paid', 'Chikkamagaluru', 'https://selfregistration.cowin.gov.in/'),
('Prashamani Hospital', 'Paid', 'Chikkamagaluru', 'https://selfregistration.cowin.gov.in/'),
('Pushpa Hospital', 'Paid', 'Chikkamagaluru', 'https://selfregistration.cowin.gov.in/'),
('Sri Maruthi Hospital', 'Paid', 'Chikkamagaluru', 'https://selfregistration.cowin.gov.in/'),
('Akshay Global Hospital', 'Paid', 'Chitradurga', 'https://selfregistration.cowin.gov.in/'),
('Basaveshwara Medical College Hospital And Research', 'Paid', 'Chitradurga', 'https://selfregistration.cowin.gov.in/'),
('Basappa Multi Specialty Hospital', 'Paid', 'Chitradurga', 'https://selfregistration.cowin.gov.in/'),
('Chitradurga Multispeciality Hospital', 'Paid', 'Chitradurga', 'https://selfregistration.cowin.gov.in/'),
('Arjan Urology Centre', 'Paid', 'Chitradurga', 'https://selfregistration.cowin.gov.in/'),
('Father Muller Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Srinivas Institute of Medical Science and RC', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Chetana Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Adarsha Hospital Puttur', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Pragathi Speciality Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Abhaya Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('JYOTHI HOSPITAL LAILA BELTHANGADY', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Fr L M Pinto Health Centre Charitable Trust', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Somayaji Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Alvas Health Centre', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Sri Krishna Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Benaka Health Centre', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Shri Dharmasthala Manjunatheshwara Hospital Ujire SDM Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Mahaveer Medical Centre', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Dhanvantari Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('KVG Medical College And Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('TARA HOSPITAL', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Kmc Hospital New', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Kmc Hospital Attavar', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Mangalore Institute Of Oncology', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Prasad Netralaya', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Indiana Hospital And Heart Institute Ltd', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Omega Hospital Pvt Ltd Mangalore', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Father Muller Medical College Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Unity Hospital Unit Of UCHS', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Yenepoya Specialty Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('A J Hospital And Research Centre', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Kanachur Hospital And Research Centre', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Justice Ks Hegde Charitable Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Yenepoya Medical College Hospital', 'Paid', 'Dakshina Kannada', 'https://selfregistration.cowin.gov.in/'),
('Gurushree Hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Latha Nursing Home', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('City Central Hospital Private Limited', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Aaraike Super Specility Hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Spandana Urology Centre', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Suchethana Hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Vishwaradhya Cancer Hospital And Reserch Institute', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Bapuji Hospital Davanagere', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Sukshema Hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Bapuji Child Health', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Nayana Super Speciality Eye Hospital And Research', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Ashraya Hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Kadali Niggamma Memorial Hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Davangere Netralaya', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Sanjeevini hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Ss Narayana Hrudayalaya', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('S S Institute Of Medical Sciences', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Apoorva Multispeciality hospital', 'Paid', 'Davanagere', 'https://selfregistration.cowin.gov.in/'),
('Vithalinstitute Of Child Health And Speciality Ce', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Sdm College Of Medical Sciences And Hospital', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('SDM Narayana Hrudayalaya', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Shivakrupa Hospital And Intensive Care Unit Hubli', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Ashoka Hospital', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Nalwad Multispeciality Hospital And Research Centre', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Vithoba Memorial Hospital Vithoba Netralaya', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Shri Balaji Institute Of Neuro Sciences And Traum', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Shakuntala Memorial Hospital And Research Centre', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('M M JOSHI EYE INSTITUTE', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Karnataka Cancer Therapy And Research Institute', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Jayapriya Hospital', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('HCG NMR Curie Centre Of Oncology', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('VIHAAN HEART CARE PVT LTD', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Disha Superspeciality Eye Hospital Research Centre', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Vivekanand General Hospital', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('SECURE HOSPITAL', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('SUCHIRAYU HEALTH CARE SOLUTIONS HOSPITAL', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Tatwadarsha Hospital', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('SANJEEVINI SPECIALITY HOSPITAL', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('Hubli super specialty hospital', 'Paid', 'Dharwad', 'https://selfregistration.cowin.gov.in/'),
('L Y Desai Memorial Sparsh Multispeciality Hospital', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Mahatma Gandhi Multi Specility Hospital', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Aashraya Hospital', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Dr N B Patil Hospital', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Vaatsalya HealthCare Solutions Pvt Ltd', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('C S I BASEL MISSION HOSPITAL', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Dr Huilgol City Hospital Gadag', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Shree Anil Kale Memorial Ashirwad Nursing Home', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('K H Patil Hospital And Research Institute', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Rajiv Gandhi Education Societys Hospital Ron', 'Paid', 'Gadag', 'https://selfregistration.cowin.gov.in/'),
('Smt Savithramma Shanasappa Hospital Research Cen', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Nagesh Hospital', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Janatha Hospital And Research Center', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Janapriya Hospital', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Vaatsalya Hospital', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Mani Super Speciality Hospital And Research Instit', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Mangala Hospital', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Hemavathi Hospital', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('SSM Hospital', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Janapriya Indiana Heart Lifeline', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Manjunatha Hospital', 'Paid', 'Hassan', 'https://selfregistration.cowin.gov.in/'),
('Malladad Rudramma Memorial Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Renuka Eye Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Veerapur Multi Speciality Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Sri Kantesh Hospital And Orthopedic Truma Care Centre', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Parvathamma Mahadevagouda Heggeri Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Sri Sooryanarayana Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Shushroosha Drgvpandit Memorial Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Shivakrupa Hospital Ranebennur', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Sri Nandi Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Om Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Sri Sai Speciality Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Sri Laxmi Surgical Trauma Ortho And Multispeciality Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Shakunthala Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Shakuntala hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Kelagar Medical Center', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Patil Maternity And Children Hospital', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Mruthyunjaya Nursing Home', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('J R Nursing Home', 'Paid', 'Haveri', 'https://selfregistration.cowin.gov.in/'),
('Chirayu Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Medicare Multispeciality Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Gulbarga Heart Foundation', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Dr Patils Ent Clinic Speech And Hearing Centre', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Netrajyothi Eye Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Shree Basavalingappa Nisty Memorial Heart Centre', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Patil Nursing Home', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Sidrameshwar Eye Clinic', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Raj Laxmi Kidney Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('United Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('HCG Cancer Centre Gulbarga', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Bhoruka Netralaya', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Khaja Banda Nawaz Teaching And General Hopital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Kamal Eye Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Chirannjevi Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Devatha hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Kamareddy Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Jeevan Care Maternity And General Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Shri Shivshankrappa Nandyal Eye Care Center', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Bahmani Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Satya Uro Care And Multi Speciality Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Mother Theresa Charitable Hospital Trust', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Tippusultan Maternity and General Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Girish Kidney Foundation And Multispeciality Hospi', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('Basaveshwar Teaching And General Hospital', 'Paid', 'Kalaburagi', 'https://selfregistration.cowin.gov.in/'),
('SHREYA HOSPITAL', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('New Kolar Nursing Home', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('Surya Eye And Skin Care Hospital', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('R L Jalappa Narayana Hrudayalaya Heart Centre', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('R L Jalappa Hospital And Research Centre', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('Sambhram Institute of Medical Science and Research', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('Sanjana Hospital', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('Poornima Hospital And Maternity Centre', 'Paid', 'Kolar', 'https://selfregistration.cowin.gov.in/'),
('Maruthi Eye And Dental Hospital Gangavathi', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Shree Mallikarjuna Multi Speciality Hospital', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Tejeswini Childran Hospital', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Amar Hospital Child Care Clinic', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Yashodha hospital', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Lions Club Charitable Trust Koppal', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('KS Health Care', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Vaatsalya Hospital', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Dr Subhas Kakhandki Eye Hospital', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Viveka Shrinivas Eye Hospital Hanamasagar', 'Paid', 'Koppal', 'https://selfregistration.cowin.gov.in/'),
('Trinetra Eye Hospital', 'Paid', 'Mandya', 'https://selfregistration.cowin.gov.in/'),
('Archana Hospital', 'Paid', 'Mandya', 'https://selfregistration.cowin.gov.in/'),
('Belaku Eye Hospital', 'Paid', 'Mandya', 'https://selfregistration.cowin.gov.in/'),
('Mandya Ent Care Centre And Hospital', 'Paid', 'Mandya', 'https://selfregistration.cowin.gov.in/'),
('G Madegowda Super Speciality Hospital', 'Paid', 'Mandya', 'https://selfregistration.cowin.gov.in/'),
('Sri Lakshmi Venkatesh Nursing Home', 'Paid', 'Mandya', 'https://selfregistration.cowin.gov.in/'),
('Sri Adichunchanagiri Hospital And Research Center', 'Paid', 'Mandya', 'https://selfregistration.cowin.gov.in/'),
('DRM Multi Speciality Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Jagadguru Sri Shivarathreeshwara Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Vasan Eye Care Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Nandhana Super Speciality Eye care Pvt Ltd', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Sigma Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Shree Mahadeshwara Nursing Home', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Shubhodaya Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Brindavan Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Nagaraje Gowda Memorial Hospital Phc', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('St Josephs Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Bibi Ayesha Milli Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Supriya Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Bharath Hospital Institute Of Oncology', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Clearmedi Radiant Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Pralaksha Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Narayana Hrudayalaya Surgical Hospital Pvt Ltd', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Annapoorna eye Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Suyog Hospital unit of Arogya yoga samsthe', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Sindhu Eye Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Bhanavi Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Apollo BGS Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Vidyaranya Hospital Pvt Limited', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Amritakripa Charitable Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Nirmala Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Sompura Basappa Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Cauvery Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Vivekananda Memorial Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Nanjamma Javaregowdas Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('Krishna Hospital', 'Paid', 'Mysuru', 'https://selfregistration.cowin.gov.in/'),
('MK Bhandari Hospital', 'Paid', 'Raichur', 'https://selfregistration.cowin.gov.in/'),
('Hosamani Hospital', 'Paid', 'Raichur', 'https://selfregistration.cowin.gov.in/'),
('Navodaya Medical College Hospital Raichur', 'Paid', 'Raichur', 'https://selfregistration.cowin.gov.in/'),
('Shri Renuka Multi Specialty Hospital', 'Paid', 'Raichur', 'https://selfregistration.cowin.gov.in/'),
('Shanti Hospital', 'Paid', 'Raichur', 'https://selfregistration.cowin.gov.in/'),
('Dr Chandramma Dayanad Sagar Institute of Medical Education', 'Paid', 'Ramanagara', 'https://selfregistration.cowin.gov.in/'),
('Belaku Eye Hospital', 'Paid', 'Ramanagara', 'https://selfregistration.cowin.gov.in/'),
('Mallikarjuna Nursing Home', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Maax Super Speciality Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Malnad Ent Institute Research Centre', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Sarji Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Sagar Nursing Home and Laser Center', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Kottureshwara Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Subbaiah Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Unity Center For Advanced Pediatric Care', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Metrounited Healthcare', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Sri Basaveshwara Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Ravi Polyclinic Maternity And Nursing Home', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Sindhu Urology Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Skkmt Sankara Eye Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Sahyadri Narayana Hrudayalaya', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Nanjappa Life Care', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Subbaaiah Medical College Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Malnad Institute Of Oncology', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Nayana Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Durga Nursing Home', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Bhadra Nursing Home', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Nirmala Hospital', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Anuradha Nursing Home', 'Paid', 'Shivamogga', 'https://selfregistration.cowin.gov.in/'),
('Swami Vivekananda Integrated Rural Health CentreShree Sharadadevi Eye Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Sri Sai Nethralaya And Dental Care', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Madilu Childrens Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Surya Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Mookambika Modi Eye Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Tumkur Speciality Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Ganadal Ent And Dental Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Kaushal Dental Care', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Shridevi Institute Of Medical Sciences', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Secretary Sri Siddartha Acadamy Of Higher Education', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Mm Multispeciality Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Raghu Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Sharada Hospital For Mother and child', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Swathi Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Shri Vijaya Nursing Home', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Kumar hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Mudra hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Chiranjeevi Nursing Home', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Sri Sai Ganga Nursing Home', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Spandana Nursing Home', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Sakshya Eye Care And Dental Hospital', 'Paid', 'Tumakuru', 'https://selfregistration.cowin.gov.in/'),
('Spandana Hospital Karkala', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Nitte Gajria Speciality Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('PRASAD NETRALAYA', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('New City Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Mitra Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Adarsha Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Manjunatha Eye Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Dr TMA Pai Hospital Udupi', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Sunag Ortho Care and Multispeciality Centre', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Hitech Medicare Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Kasturba Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Adarsha Hospital Kundapura', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Sri Devi Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Chinmayi Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Sri Manjunatha Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Sri Matha Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Vivek Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Pranav Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Mahesh Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Dr N R Acharya Memorial Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('Surgeons Hospital', 'Paid', 'Udupi', 'https://selfregistration.cowin.gov.in/'),
('St Ignatius Hospital', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Sridevimultispeciality Hospital', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Dr V K B Balkur Memorial Hospital', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Shri Sharada Nursing Home', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Dr Janu Mankikars Maternity And Nursing Home', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Achut Pandit Hospital', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Canara Health Care Centre', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Ramleela Hospital', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('24 7 Hi Tech Life Line', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('RNS Hospital Murudeshwar', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('SAI NETRALAYA', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Vishwa Seva Samitis Rotary Charitable Hospital', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Tss Shripad Hegde Kadave Institute Of Medical Scie', 'Paid', 'Uttara Kannada', 'https://selfregistration.cowin.gov.in/'),
('Akki Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Mahaldar Children Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Hussain Multispeciality Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Dr Munir Bangi Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Kembhavi Eye Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Basanagouda Patil Sunag Memorial Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Luqman Unani Medical College Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Korbu Womens Care Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Anugraha Eye Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Vasudev Hospitals Pvt Ltd', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Yashoda Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Mathoshree Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Patil Multispeciality Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Sparsha Multispeciality Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Dr Bidaris Ashwini Hospital Bijapur', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Sanjeevini Superspeciality Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Blde University Shri Bm Patil Medical College Hosp', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Tanga Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('ANNAPURNA MULTI SPECIALTY HOSPITAL', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Vaibhav orthopaedic And Dental Care Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Bijapur Kidney Foundation', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('alnabi hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Mudhol Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Choudhari Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Al Ameen Medical College Hospital', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('Shri Bhagyavanti Multispeciality Hospital And Rc', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('SHRI SAI HOSPITAL', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/'),
('DR G R BHAT HOSPITAL TALIKOT', 'Paid', 'Vijayapura', 'https://selfregistration.cowin.gov.in/');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`refno`),
  ADD KEY `refno` (`refno`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `refno` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;";
$res = sqli_query($conn,$sql);


?>




